### ISSUE TITLE
Part 8/2 Error in comments

### ISSUE THREAD

**Issue by ArtieLiu** [rage/java-programming#168]
The first example in "Hash map as an Instance Variable" contains wrong comments.
![image](https://user-images.githubusercontent.com/62593089/84564779-114ac080-ad97-11ea-84f2-3117211e09f2.png)

Should be:
![image](https://user-images.githubusercontent.com/62593089/84564941-2d029680-ad98-11ea-8212-34f0b28078bf.png)

Tested with the following code:
![image](https://user-images.githubusercontent.com/62593089/84564986-95ea0e80-ad98-11ea-943d-661b2d350cfb.png)

**Comment by S4ndyk** [comment]
Thanks. Fixed this in: https://github.com/rage/java-programming/commit/0fc6fc219bd6478239cc30aaf4da48a35d7ca583
