### ISSUE TITLE
Part-10 handling collections as streams quiz filter correct answer 

### ISSUE THREAD

**Issue by mhmtaliakbay** [rage/java-programming#218]
the correct answer should have been 0 but answer is shown 4

<img width="531" alt="issue" src="https://user-images.githubusercontent.com/23544693/90954937-b1048900-e481-11ea-81e6-3830df13c271.PNG">

**Comment by aadvdh** [comment]
The answer is actually 4. It asks how many numbers are left before the second filter. Which in this case is 0,1,2,3. After the second filter the answer is indeed 0.
