### ISSUE TITLE
Part 11 - ex. 12 Sensors and Temperatures

### ISSUE THREAD

**Issue by Stellaway** [rage/java-programming#313]
![image](https://user-images.githubusercontent.com/40556813/128619922-85f2d994-a311-46b6-9095-0318c3846729.png)
An error says a list should be empty, but it looks like it shouldn't.

**Comment by Stellaway** [comment]
![image](https://user-images.githubusercontent.com/40556813/128619956-a75dd6da-271a-4804-a953-91cfec8ff09d.png)
This is what it reads if I return a new ArrayList instead.

**Comment by ConcernedHobbit** [comment]
Note that you haven't taken any readings with the StandardSensors, and therefore this behaviour is intended.
A faster way of communication is our Telegram group -- the link is in the course material's "Support and assistance" section.
